# Generated by Django 4.2 on 2023-04-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='gps_latitude',
            field=models.DecimalField(decimal_places=5, default=39.6, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='gps_longtitude',
            field=models.DecimalField(decimal_places=5, default=40.5, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device_group',
            name='device_count',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
